# Generated by Django 3.1.3 on 2022-10-22 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acueducto',
            fields=[
                ('IdAcueducto', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('DirOficina', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='usuarios/usuario.png', upload_to='usuarios')),
                ('Relegal', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=11)),
                ('Estado', models.CharField(choices=[('En Servicio', 'En Servicio (ES)'), ('Baja Presion', 'Baja Presion (BP)'), ('Suspendido', 'Suspendido (SP)'), ('Daño Critico', 'Daño Critico (DC)')], default='ES', max_length=30, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Lista de Acueductos',
                'verbose_name_plural': 'Lista de Acueductos',
            },
        ),
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('IdCertificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Nit', models.CharField(max_length=10)),
                ('NombreEmpresa', models.CharField(max_length=300)),
                ('Estado', models.CharField(choices=[('No certificada', 'No certificada'), ('Certificada', 'Certificada')], max_length=25)),
                ('Soporte', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Certificacion',
                'verbose_name_plural': 'Listado de certificaciones',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('IdCiclo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Listado de ciclos',
                'verbose_name_plural': 'Lista de Ciclos',
            },
        ),
        migrations.CreateModel(
            name='Cierres',
            fields=[
                ('IdCierre', models.AutoField(primary_key=True, serialize=False)),
                ('Ingresos', models.CharField(max_length=100)),
                ('Gastos', models.CharField(max_length=100)),
                ('Presupuesto', models.CharField(max_length=100)),
                ('Ciclo', models.CharField(max_length=100)),
                ('Ano', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('NoRecaudo', models.CharField(max_length=100)),
                ('Recaudado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cierre mensual',
                'verbose_name_plural': 'Lista de cierres mensuales',
            },
        ),
        migrations.CreateModel(
            name='CobroOrdenes',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Estado', models.CharField(max_length=30)),
                ('Valor', models.CharField(max_length=30)),
                ('IdOrdenT', models.CharField(max_length=30)),
                ('TipoOrden', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cobro orden',
                'verbose_name_plural': 'Cobro ordenes SR',
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('IdEstadoCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.IntegerField(default=0)),
                ('Estado', models.CharField(max_length=100)),
                ('FechaActualizacion', models.DateTimeField(auto_now=True)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de cuenta',
                'verbose_name_plural': 'Estados de cuenta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('IdFactura', models.AutoField(primary_key=True, serialize=False)),
                ('Matricula', models.CharField(max_length=100, null=True)),
                ('Estado', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100, null=True)),
                ('IdEstadoCuenta', models.CharField(max_length=100, null=True)),
                ('nombretitular', models.CharField(max_length=100, null=True)),
                ('ciclo', models.CharField(max_length=100, null=True)),
                ('Estrato', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('casa', models.CharField(max_length=10, null=True)),
                ('piso', models.CharField(max_length=10, null=True)),
                ('direccionentrega', models.CharField(max_length=100, null=True)),
                ('estadoservicio', models.CharField(max_length=100, null=True)),
                ('tiposerivio', models.CharField(max_length=50, null=True)),
                ('periodofacturado', models.CharField(max_length=50, null=True)),
                ('aporteporconsumo', models.CharField(max_length=100, null=True)),
                ('conceptomatricula', models.CharField(max_length=100, null=True)),
                ('cuotasmatricula', models.CharField(max_length=100, null=True)),
                ('reconexion', models.CharField(max_length=100, null=True)),
                ('suspencion', models.CharField(max_length=100, null=True)),
                ('TotalConsumo', models.CharField(max_length=100, null=True)),
                ('referencias', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('valor', models.CharField(max_length=100, null=True)),
                ('facturasvencidas', models.CharField(max_length=100, null=True)),
                ('FechaExpe', models.DateTimeField(auto_now=True)),
                ('FechaLimite', models.DateTimeField(null=True)),
                ('Fechasuspencion', models.DateTimeField(null=True)),
                ('OtrosCobros', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
                ('IdCiclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.ciclo')),
            ],
            options={
                'verbose_name': 'Generar factura',
                'verbose_name_plural': 'Lista de facturas',
            },
        ),
        migrations.CreateModel(
            name='NovedadesGenerales',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Novedad general',
                'verbose_name_plural': 'Novedades generales',
            },
        ),
        migrations.CreateModel(
            name='NovedadesSistema',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('IdPoblacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de poblacion',
                'verbose_name_plural': 'Tipos de poblacion',
            },
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('IdPqrs', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=5000, null=True)),
                ('FechaRadicado', models.DateTimeField(auto_now_add=True)),
                ('Soporte', models.FileField(null=True, upload_to='pqrs/')),
                ('CedulaNit', models.CharField(max_length=15, null=True)),
                ('NombreCompleto', models.CharField(max_length=100, null=True)),
                ('Telefono', models.CharField(max_length=10, null=True)),
                ('Correo', models.EmailField(max_length=60, null=True)),
                ('Direccion', models.CharField(max_length=200, null=True)),
                ('TipoSolicitud', models.CharField(max_length=50, null=True)),
                ('Estado', models.CharField(choices=[('Cerrada', 'Cerrada')], max_length=40)),
                ('Anonimo', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Pqrs',
                'verbose_name_plural': 'Pqr',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('IdPropietario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('NoTelefono', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=150, null=True)),
                ('IdPoblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.poblacion')),
            ],
            options={
                'verbose_name': 'Lista de Propietarios',
                'verbose_name_plural': 'Lista de Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nit', models.CharField(max_length=30)),
                ('Razonsocial', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Telefono', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Tipoproveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('IdTarifa', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=15)),
                ('Mantenimiento', models.CharField(max_length=15)),
                ('Recargo', models.CharField(max_length=15)),
                ('FechaInicial', models.DateTimeField()),
                ('FechaFinal', models.DateTimeField()),
                ('Ano', models.CharField(max_length=4, null=True)),
                ('consumomin', models.IntegerField(null=True)),
                ('consumotipo1', models.IntegerField(null=True)),
                ('consumotipo2', models.IntegerField(null=True)),
                ('Potipo1', models.FloatField(max_length=5, null=True)),
                ('Potipo2', models.FloatField(max_length=5, null=True)),
                ('TarifaReconexion', models.CharField(max_length=4, null=True)),
                ('TarifaSuspencion', models.CharField(max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Listado de Tarifas',
            },
        ),
        migrations.CreateModel(
            name='ValorMatricula',
            fields=[
                ('IdValor', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=10)),
                ('Fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'valor matricula',
                'verbose_name_plural': 'listado de valor de matricula',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('IdVivienda', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Direccion', models.CharField(choices=[('Pasonivel Viejo', 'Sector pasonivel viejo'), ('Pasonivel Destapada', 'Sector pasonivel destapada'), ('Caimalito Centro', 'Sector caimalito centro'), ('Barrio Nuevo', 'Sector barrio nuevo'), ('20 de julio', 'Sector 20 de julio'), ('Pasonivel la loma', 'Sector pasonivel la loma'), ('Hacienda', 'Hacienda'), ('Via nacional', 'Sector Via nacional'), ('Caimalito centro dos', 'Sector caimalito centro dos'), ('Destapada', 'Sector destapada')], max_length=20)),
                ('NumeroCasa', models.CharField(max_length=8)),
                ('Piso', models.CharField(blank=True, max_length=2, null=True)),
                ('Ciclo', models.CharField(choices=[('2', 'Ciclo pasonivel viejo'), ('3', 'Ciclo Barrio nuevo'), ('4', 'Ciclo caimalito via principal'), ('5', 'Ciclo 20 julio')], max_length=40)),
                ('TipoInstalacion', models.CharField(choices=[('Residencial', 'Instalacion Residencial (Res)'), ('Comercial', 'Instalacion Comercial (Com)'), ('Industrial', 'Instalacion Industrial (Ind)')], default='Res', max_length=60)),
                ('Estrato', models.CharField(choices=[('1', 'Bajo-bajo (1)'), ('2', 'Bajo (2)'), ('3', 'Medio-bajo  (3)'), ('Co', 'Comercial (Co)'), ('Ins', 'Industrial (Ins)')], default='1', max_length=60)),
                ('EstadoServicio', models.CharField(choices=[('Operativo', 'Operativo (OP)'), ('Suspendido', 'Suspendido (SP)'), ('Mantenimiento', 'Mantenimiento (MT)'), ('Retirado', 'Retirado  (RD)'), ('Conexion nueva', 'Conexion nueva (CN)')], default='EC', max_length=60)),
                ('MatriculaAnt', models.CharField(max_length=4)),
                ('InfoInstalacion', models.CharField(choices=[('Instalacion Empotrada', 'Instalacion Empotrada'), ('Instalacion a la vista', 'Instalacion a la vista'), ('Instalacion Mixta', 'Instalacion Mixta')], max_length=30)),
                ('ProfAcometida', models.CharField(max_length=4)),
                ('CantHabitantes', models.CharField(max_length=2)),
                ('FichaCastral', models.CharField(max_length=26, null=True)),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto')),
                ('IdPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.propietario')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Viviendas',
                'verbose_name_plural': 'Lista de Viviendas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('fotoUsuario', models.ImageField(default='usuarios/usuario.png', upload_to='usuarios')),
                ('TipoUsuario', models.CharField(blank=True, choices=[('Presidente', 'Presidente (Pdte)'), ('Cartera', 'Cartera (Ct)'), ('Operario', 'Operario (Ope)'), ('Auxiliar', 'Auxiliar (Aux)'), ('Administrador de sistemas', 'Administrador de sistemas(Dir)')], default='Auxiliar', max_length=100, null=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Departamento', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto')),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos usuario',
                'verbose_name_plural': 'Datos usuarios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudGastos',
            fields=[
                ('IdSoGa', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('TipoSolicitud', models.CharField(max_length=50)),
                ('Valor', models.CharField(max_length=10)),
                ('Estado', models.CharField(choices=[('Anulada', 'Anular solicitud'), ('Aprobada', 'Aprobar solicitud')], max_length=15)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('AreaResponsable', models.CharField(max_length=100)),
                ('NumeroFactura', models.CharField(max_length=10)),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de gasto',
                'verbose_name_plural': 'solicitudes de gastos',
            },
        ),
        migrations.CreateModel(
            name='RespuestasPqrs',
            fields=[
                ('IdRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('Soporte', models.FileField(null=True, upload_to='respuestaspqr/')),
                ('IdPqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.pqrs')),
            ],
            options={
                'verbose_name': 'Respuestas',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AddField(
            model_name='pqrs',
            name='usuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario'),
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('IdPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('TipoPermiso', models.CharField(choices=[('AccessPanel', 'Acceso - panel de administracion - AccessPanel'), ('AVLV', 'Acceso - Ver listado viviendas - AVLV'), ('AVF', 'Acceso - Ver factura - AVF'), ('AB', 'Acceso - Buscador - AB'), ('ALS', 'Acceso - Listado de suscriptores - ALS'), ('ALP', 'Acceso - Listado de predios - ALP'), ('AR', 'Acceso - Reportes - AR'), ('ACC', 'Acceso - Cuentas de cobro - ACC'), ('GCA', 'Generar - Cobro de aportes - GCA'), ('AIS', 'Agregar - Informacion suscriptor - AIS'), ('AIP', 'Agregar - Informacion predio - AIP'), ('AMFV', 'Acceso - Modulo de facturas vencidas - AMFV'), ('AGF', 'Acceso - Generador de facturas - AGF'), ('GF', 'Generar - Facturas - GF'), ('AF', 'Acceso - Anular facturas - AF'), ('AC', 'Acceso - Consumos - AC'), ('ASR', 'Acceso - Suspenciones y Reconexiones - ASR'), ('ACP', 'Acceso - Control presupuestal - ACP'), ('ACF', 'Acceso - Cierre financiero - ACF'), ('APQRS', 'Acceso - PQRS - APQRS')], max_length=50)),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('IdPago', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPago', models.DateTimeField(auto_now=True)),
                ('Ano', models.CharField(max_length=4)),
                ('Descripcion', models.CharField(max_length=20)),
                ('ValorPago', models.CharField(max_length=10)),
                ('Efectivo', models.CharField(max_length=10)),
                ('Devuelta', models.CharField(max_length=10)),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.factura')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='PagoOrdenes',
            fields=[
                ('IdPagoSR', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPago', models.DateTimeField(auto_now=True)),
                ('Valor', models.CharField(max_length=30)),
                ('IdOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.cobroordenes')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Pago orden',
                'verbose_name_plural': 'PagoOrdenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenesSuspencion',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Deuda', models.CharField(max_length=10)),
                ('FechaExpe', models.DateTimeField(auto_now_add=True)),
                ('FechaEjecucion', models.DateTimeField()),
                ('Generado', models.CharField(max_length=60)),
                ('Estado', models.CharField(max_length=40)),
                ('UsuarioEjecuta', models.CharField(max_length=100)),
                ('IdEstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.estadocuenta')),
            ],
            options={
                'verbose_name': 'Orden de suspencion',
                'verbose_name_plural': 'Ordenes de suspencion',
            },
        ),
        migrations.CreateModel(
            name='OrdenesReconexion',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Deuda', models.CharField(max_length=10)),
                ('FechaExpe', models.DateTimeField(auto_now_add=True)),
                ('FechaEjecucion', models.DateTimeField()),
                ('Generado', models.CharField(max_length=20)),
                ('Estado', models.CharField(max_length=40)),
                ('UsuarioEjecuta', models.CharField(max_length=30)),
                ('IdEstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.estadocuenta')),
            ],
            options={
                'verbose_name': 'Orden de Reconexion',
                'verbose_name_plural': 'Ordenes de Reconexion',
            },
        ),
        migrations.CreateModel(
            name='NovedadVivienda',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('Valor', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('EstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.estadocuenta')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
            options={
                'verbose_name': 'lista de Novedades',
                'verbose_name_plural': 'Lista de Novedades Viviendas',
            },
        ),
        migrations.CreateModel(
            name='NovedadPropietario',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto')),
                ('IdPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.propietario')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Novedades',
                'verbose_name_plural': 'Lista de Novedades propietarios',
            },
        ),
        migrations.CreateModel(
            name='Medidores',
            fields=[
                ('IdMedidor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=20)),
                ('LecturaInicial', models.CharField(max_length=6)),
                ('AnoFabricacion', models.CharField(max_length=4)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Listado de Medidores',
            },
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='IdVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda'),
        ),
        migrations.CreateModel(
            name='ConfirCerti',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('IdCertificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.certificaciones')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
            options={
                'verbose_name': 'confirmacion',
                'verbose_name_plural': 'listado de confirmaciones',
            },
        ),
        migrations.AddField(
            model_name='cobroordenes',
            name='IdEstadoCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.estadocuenta'),
        ),
        migrations.CreateModel(
            name='CobroMatricula',
            fields=[
                ('IdCobroM', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Estado', models.CharField(max_length=15)),
                ('CantCuotas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36')], max_length=10)),
                ('CuotasPendientes', models.CharField(max_length=10)),
                ('ValorPendiente', models.CharField(max_length=50)),
                ('Cuota', models.CharField(max_length=50)),
                ('IdValor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.valormatricula')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Cobro matricula',
                'verbose_name_plural': 'Cobro matriculas',
            },
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='IdVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda'),
        ),
        migrations.CreateModel(
            name='AsignacionExterna',
            fields=[
                ('IdAsigExt', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=10)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Soporte', models.FileField(upload_to='AsignacionExterna/')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto externo',
                'verbose_name_plural': 'Asignacion de presupuesto externo',
            },
        ),
        migrations.CreateModel(
            name='ArchivosAcueducto',
            fields=[
                ('IdArchivo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreArchivo', models.CharField(max_length=100, null=True)),
                ('Carpeta', models.CharField(max_length=100, null=True)),
                ('Archivo', models.FileField(null=True, upload_to='archivos/')),
                ('FechaSubida', models.DateTimeField(auto_now=True)),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('IdArchivo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreArchivo', models.CharField(max_length=100, null=True)),
                ('Archivo', models.FileField(null=True, upload_to='documentosusuarios/')),
                ('Carpeta', models.CharField(max_length=100, null=True)),
                ('FechaSubida', models.DateTimeField(auto_now=True)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.AddField(
            model_name='acueducto',
            name='IdTarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.tarifa'),
        ),
    ]
