# Generated by Django 2.2.4 on 2019-12-25 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acueducto',
            fields=[
                ('IdAcueducto', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('DirOficina', models.CharField(max_length=100)),
                ('Relegal', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Lista de Acueductos',
                'verbose_name_plural': 'Lista de Acueductos',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('IdPropietario', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('NoTelefono', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=150)),
            ],
            options={
                'verbose_name': 'Lista de Propietarios',
                'verbose_name_plural': 'Lista de Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('IdVivienda', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=200)),
                ('NumeroCasa', models.CharField(max_length=8)),
                ('TipoInstalacion', models.CharField(max_length=60)),
                ('Estrato', models.CharField(max_length=60)),
                ('EstadoServicio', models.CharField(max_length=60)),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Acueducto')),
                ('IdPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Propietario')),
                ('Usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Viviendas',
                'verbose_name_plural': 'Lista de Viviendas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('foto_usuario', models.ImageField(upload_to='')),
                ('TipoUsuario', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos usuario',
                'verbose_name_plural': 'Datos usuarios',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=8)),
                ('IdPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Propietario')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda')),
                ('Usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Viviendas',
                'verbose_name_plural': 'Lista de Viviendas',
            },
        ),
    ]
