# Generated by Django 2.2.4 on 2020-04-13 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAAL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('IdArchivo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreArchivo', models.CharField(max_length=100, null=True)),
                ('Archivo', models.FileField(null=True, upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('IdCiclo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=10)),
                ('FechaIni', models.DateTimeField()),
                ('FechaFin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Listado de ciclos',
                'verbose_name_plural': 'Lista de Ciclos',
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('IdEstadoCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.IntegerField(default=0)),
                ('Estado', models.CharField(max_length=100)),
                ('IdCiclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Ciclo')),
            ],
            options={
                'verbose_name': 'Estado de cuenta',
                'verbose_name_plural': 'Estados de cuenta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('IdFactura', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=100)),
                ('FechaExpe', models.DateTimeField(auto_now_add=True)),
                ('FechaLimite', models.DateTimeField()),
                ('Total', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Generar factura',
                'verbose_name_plural': 'Lista de facturas',
            },
        ),
        migrations.CreateModel(
            name='NovedadPropietario',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lista de Novedades',
                'verbose_name_plural': 'Lista de Novedades propietarios',
            },
        ),
        migrations.CreateModel(
            name='NovedadVivienda',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lista de Novedades',
                'verbose_name_plural': 'Lista de Novedades Viviendas',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.EstadoCuenta')),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Factura')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pago',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuid',
            new_name='usuid',
        ),
        migrations.RenameField(
            model_name='vivienda',
            old_name='Usuid',
            new_name='usuid',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto_usuario',
        ),
        migrations.AddField(
            model_name='acueducto',
            name='Estado',
            field=models.CharField(choices=[('En Servicio', 'En Servicio (ES)'), ('Baja Presion', 'Baja Presion (BP)'), ('Suspendido', 'Suspendido (SP)'), ('Daño Critico', 'Daño Critico (DC)')], default='ES', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='acueducto',
            name='Mapa',
            field=models.ImageField(default='usuarios/mapa.png', upload_to='usuarios'),
        ),
        migrations.AddField(
            model_name='acueducto',
            name='Tarifa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='Direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='IdAcueducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Acueducto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fotoUsuario',
            field=models.ImageField(default='usuarios/usuario.png', upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='acueducto',
            name='IdAcueducto',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='Email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='IdPropietario',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Admin', 'Administrador del sistema (AD)'), ('Consultor', 'Consultor (CT)'), ('Fontanero', 'Fontanero (FT)')], default='Consultor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('OP', 'Operativo (OP)'), ('SP', 'Suspendido (SP)'), ('RD', 'Retirado  (RD)'), ('EC', 'En Contruccion (EC)')], default='EC', max_length=60),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Estrato',
            field=models.CharField(choices=[('1', 'Bajo-bajo (1)'), ('2', 'Bajo (2)'), ('3', 'Medio-bajo  (3)'), ('4', 'Medio (4)'), ('5', 'Medio-Alto (5)'), ('6', 'Alto (6)')], default='1', max_length=60),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='IdVivienda',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='TipoInstalacion',
            field=models.CharField(choices=[('Residencial', 'Instalacion Residencial (Res)'), ('Comercial', 'Instalacion Comercial (Com)')], default='Res', max_length=60),
        ),
        migrations.DeleteModel(
            name='Novedad',
        ),
        migrations.AddField(
            model_name='novedadvivienda',
            name='IdAcueducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Acueducto'),
        ),
        migrations.AddField(
            model_name='novedadvivienda',
            name='IdVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda'),
        ),
        migrations.AddField(
            model_name='novedadvivienda',
            name='usuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedadpropietario',
            name='IdAcueducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Acueducto'),
        ),
        migrations.AddField(
            model_name='novedadpropietario',
            name='IdPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Propietario'),
        ),
        migrations.AddField(
            model_name='novedadpropietario',
            name='usuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='IdVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='IdPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Propietario'),
        ),
    ]
