# Generated by Django 3.1.3 on 2022-10-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='IdEstadoCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.estadocuenta'),
        ),
    ]
