# Generated by Django 3.1.3 on 2024-04-25 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='FechaExpe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
