# Generated by Django 3.1.3 on 2024-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='FechaActualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='FechaIngreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
