# Generated by Django 3.1.3 on 2024-03-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudgastos',
            name='IdProveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAL.proveedor'),
        ),
    ]
