# Generated by Django 3.1.3 on 2024-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0002_auto_20240807_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('Operativo', 'Operativo')], max_length=60),
        ),
    ]
