# Generated by Django 3.1.3 on 2022-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0002_auto_20221022_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='resta',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
