# Generated by Django 3.0.5 on 2020-06-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0002_auto_20200412_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('IdTarifa', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=8)),
                ('FechaInicial', models.DateTimeField()),
                ('FechaFinal', models.DateTimeField()),
                ('Ano', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='acueducto',
            name='Tarifa',
        ),
        migrations.AddField(
            model_name='acueducto',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador del sistema (AD)'), ('Cartera', 'Cartera (CT)'), ('Operario', 'Operario (OP)')], default='Consultor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('Operativo', 'Operativo (OP)'), ('Suspedido', 'Suspendido (SP)'), ('Retirado', 'Retirado  (RD)'), ('En contruccion', 'En Contruccion (EC)')], default='EC', max_length=60),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='TipoInstalacion',
            field=models.CharField(choices=[('Residencial', 'Instalacion Residencial (Res)'), ('Comercial', 'Instalacion Comercial (Com)'), ('Industrial', 'Instalacion Industrial (Ind)')], default='Res', max_length=60),
        ),
        migrations.AddField(
            model_name='acueducto',
            name='IdTarifa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Tarifa'),
            preserve_default=False,
        ),
    ]
