# Generated by Django 3.1.3 on 2024-03-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0002_solicitudgastos_idproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='TipoSolicitud',
            field=models.CharField(choices=[('Servicios publicos', 'Pago - servicios publicos'), ('Nomina', 'Pago - nomina'), ('Viaticos', 'Pago - viaticos'), ('Impuestos', 'Pago - impuestos'), ('Mantenimiento infrastructura', 'Pago - Mantenimiento de infraestructura'), ('Compra de materiales', 'Pago - Compra de materiales'), ('Compra de accesorios', 'Pago - Compra de accesorios'), ('Transporte', 'Pago - transporte')], max_length=50),
        ),
    ]
