# Generated by Django 3.1.3 on 2024-04-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0002_facturas_fechaexpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptosfacturados',
            name='Recargo',
            field=models.IntegerField(null=True),
        ),
    ]
