# Generated by Django 3.1.3 on 2024-04-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0003_conceptosfacturados_recargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='FechaFacturacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='Periodo',
            field=models.DateTimeField(null=True),
        ),
    ]
