# Generated by Django 3.1.3 on 2024-04-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0003_auto_20240330_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidores',
            name='IdVivienda',
        ),
    ]
