# Generated by Django 3.1.3 on 2022-10-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0003_pagos_resta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estadoservicio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tiposerivio',
        ),
    ]
