# Generated by Django 3.0.5 on 2020-06-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0003_auto_20200622_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acueducto',
            name='IdAcueducto',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
