# Generated by Django 3.1.3 on 2024-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0003_auto_20240807_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='Estrato',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Oficial', 'Oficial'), ('Comercial', 'Comercial'), ('Especial', 'Especial'), ('Industrial', 'Industrial')], default='1', max_length=60),
        ),
    ]
