# Generated by Django 3.1.3 on 2024-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0004_remove_medidores_idvivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidores',
            name='Estado',
            field=models.CharField(default='Sin asignar', max_length=35),
        ),
    ]
