# Generated by Django 3.1.3 on 2024-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0004_auto_20240807_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acueducto',
            name='Estado',
            field=models.CharField(choices=[('En Servicio', 'En Servicio (ES)')], default='ES', max_length=30, null=True),
        ),
    ]
