# Generated by Django 3.1.3 on 2022-10-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0004_auto_20221025_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Estrato',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='nombretitular',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='referencias',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='valor',
        ),
    ]
