# Generated by Django 3.0.5 on 2020-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0004_auto_20200622_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifa',
            options={'verbose_name': 'Tarifa', 'verbose_name_plural': 'Listado de Tarifas'},
        ),
        migrations.AddField(
            model_name='vivienda',
            name='Ciclo',
            field=models.CharField(choices=[('Ciclo 1', 'Troncal pasonivel viejo'), ('Ciclo 2', 'Troncal caimalito via principal'), ('Ciclo 3', 'Troncal Barrio nuevo'), ('Ciclo 4', 'Linea Auxiliar 20 julio')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='InfoInstalacion',
            field=models.CharField(choices=[('Tipo 1', 'Instalacion Empotrada'), ('Tipo 2', 'Instalacion a la vista'), ('Tipo 3', 'Instalacion Mixta')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='MatriculaAnt',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='Piso',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='PlanoIso',
            field=models.ImageField(default='usuarios/usuario.png', upload_to='usuarios'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='ProfAcometida',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Estrato',
            field=models.CharField(choices=[('1', 'Bajo-bajo (1)'), ('2', 'Bajo (2)'), ('3', 'Medio-bajo  (3)'), ('Co', 'Comercial (Co)'), ('Ins', 'Industrial (Ins)')], default='1', max_length=60),
        ),
    ]
