# Generated by Django 3.1.3 on 2024-04-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0004_auto_20240425_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciclo',
            old_name='Periodo',
            new_name='FechaPago',
        ),
    ]
