# Generated by Django 3.1.3 on 2024-08-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0005_auto_20240807_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumosMensual',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('Consumo', models.IntegerField()),
                ('promedio', models.CharField(max_length=20)),
                ('observaciones', models.CharField(max_length=350, null=True)),
                ('ano', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=20)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
    ]
