# Generated by Django 3.0.5 on 2020-06-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0005_auto_20200622_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='MatriculaAnt',
            field=models.IntegerField(null=True),
        ),
    ]
