# Generated by Django 3.1.3 on 2024-04-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0005_auto_20240425_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='FechaFacturacion',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='FechaPago',
        ),
    ]
