# Generated by Django 3.1.3 on 2024-04-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0005_medidores_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(default='Operativo', max_length=60),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('Fecha', models.DateTimeField(auto_created=True)),
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(choices=[('Asignado', 'Asignado'), ('Retirado', 'Retirado')], max_length=40)),
                ('IdMedidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.medidores')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Asignar',
                'verbose_name_plural': 'Asignados',
            },
        ),
    ]
