# Generated by Django 3.1.3 on 2022-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0005_auto_20221025_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Fechasuspencion',
        ),
        migrations.AlterField(
            model_name='factura',
            name='FechaExpe',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
