# Generated by Django 3.0.5 on 2020-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0006_auto_20200622_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='CantHabitantes',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
