# Generated by Django 3.1.3 on 2024-04-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0006_auto_20240425_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasFacturacion',
            fields=[
                ('IdRegistro', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=15)),
                ('FechaFacturacion', models.DateTimeField()),
                ('Ano', models.CharField(max_length=4)),
                ('Periodo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Listado de ciclos',
                'verbose_name_plural': 'Lista de Ciclos',
            },
        ),
        migrations.AddField(
            model_name='conceptosfacturados',
            name='Otroscobros',
            field=models.IntegerField(null=True),
        ),
    ]
