# Generated by Django 3.1.3 on 2024-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0006_consumosmensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidores',
            name='NoCertificado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
