# Generated by Django 3.1.3 on 2024-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0006_auto_20240401_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='Estado',
            field=models.CharField(choices=[('Asignado', 'Asignado'), ('Retirado', 'Retirado')], default='Asignado', max_length=40),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
