# Generated by Django 3.1.3 on 2022-10-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0006_auto_20221025_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='conceptomatricula',
            new_name='cuotamatricula',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cuotasmatricula',
        ),
    ]
