# Generated by Django 3.1.3 on 2022-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0007_auto_20221025_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='Diametro',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='InfoInstalacion',
            field=models.CharField(choices=[('Unifamiliar', 'Unifamiliar'), ('Multifamiliar', 'Multifamiliar'), ('Bifamiliar', 'Bifamiliar'), ('Comercial', 'Bifamiliar'), ('Residencial especial', 'Residencial especial'), ('Agricola', 'Agricola')], max_length=30),
        ),
    ]
