# Generated by Django 3.1.3 on 2024-04-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0007_auto_20240426_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdosPago',
            fields=[
                ('IdAcuerdo', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Estado', models.CharField(max_length=15)),
                ('IdValor', models.IntegerField(null=True)),
                ('CantCuotas', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('CuotasPendientes', models.CharField(max_length=10)),
                ('ValorPendiente', models.CharField(max_length=50)),
                ('Cuota', models.CharField(max_length=50)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
        ),
    ]
