# Generated by Django 3.0.5 on 2020-06-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0007_vivienda_canthabitantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('IdPoblacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de poblacion',
                'verbose_name_plural': 'Tipos de poblacion',
            },
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='Direccion',
        ),
        migrations.AddField(
            model_name='propietario',
            name='IdPoblacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Poblacion'),
            preserve_default=False,
        ),
    ]
