# Generated by Django 3.1.3 on 2024-09-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0007_medidores_nocertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumosmensual',
            name='CantMedidores',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
