# Generated by Django 3.1.3 on 2022-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0008_auto_20221029_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='Anonimo',
        ),
        migrations.RemoveField(
            model_name='pqrs',
            name='CedulaNit',
        ),
        migrations.RemoveField(
            model_name='pqrs',
            name='NombreCompleto',
        ),
        migrations.RemoveField(
            model_name='pqrs',
            name='Soporte',
        ),
        migrations.AddField(
            model_name='pqrs',
            name='Clasificacion',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='Nombre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='Descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='Estado',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='TipoSolicitud',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=50, null=True),
        ),
    ]
