# Generated by Django 3.1.3 on 2024-04-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0008_acuerdospago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acuerdospago',
            old_name='IdValor',
            new_name='Valor',
        ),
    ]
