# Generated by Django 3.1.3 on 2024-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0008_auto_20240401_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='Estado',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('Retirado', 'Retirado')], default='Operativo', max_length=40),
        ),
    ]
