# Generated by Django 3.1.3 on 2024-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0008_consumosmensual_cantmedidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='TipoRecaudo',
            field=models.CharField(choices=[('Aporte fijo', 'Aporte fijo'), ('Medicion', 'Medicion')], max_length=20, null=True),
        ),
    ]
