# Generated by Django 3.0.5 on 2020-06-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0008_auto_20200627_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('IdCertificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Nit', models.CharField(max_length=10)),
                ('NombreEmpresa', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=25)),
                ('Soporte', models.FileField(null=True, upload_to='documentos/')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda')),
            ],
            options={
                'verbose_name': 'Certificacion',
                'verbose_name_plural': 'Listado de certificaciones',
            },
        ),
    ]
