# Generated by Django 3.0.5 on 2020-06-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0009_certificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidores',
            fields=[
                ('IdMedidor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=20)),
                ('LecturaInicial', models.CharField(max_length=6)),
                ('AnoFabricacion', models.CharField(max_length=4)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Listado de Medidores',
            },
        ),
    ]
