# Generated by Django 3.1.3 on 2022-12-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0009_auto_20221102_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='Clasificacion',
            field=models.CharField(choices=[('Atencion de daño - Externo', 'Atencion de daño - Externo'), ('Atencion de daño - Interno', 'Atencion de daño - Interno'), ('Facturacion', 'Facturacion'), ('Administracion', 'Administracion'), ('Multas', 'Multas'), ('Tesoreria', 'Tesoreria')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='InfoInstalacion',
            field=models.CharField(choices=[('Unifamiliar', 'Unifamiliar'), ('Unifamiliar', 'Unifamiliar'), ('Multifamiliar', 'Multifamiliar'), ('Bifamiliar', 'Bifamiliar'), ('Comercial', 'Comercial'), ('Especial', 'Especial'), ('Agricola', 'Agricola')], max_length=30),
        ),
    ]
