# Generated by Django 3.1.3 on 2024-04-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0009_auto_20240401_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('Lecturaactual', models.IntegerField(max_length=20)),
                ('Lecturaanterior', models.IntegerField(max_length=20)),
                ('Consumo', models.IntegerField(max_length=20)),
                ('promedio', models.CharField(max_length=20)),
                ('observaciones', models.CharField(max_length=350, null=True)),
                ('diasconsumo', models.CharField(max_length=10)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('IdMedidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.medidores')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
    ]
