# Generated by Django 3.1.3 on 2024-04-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0009_auto_20240426_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdospago',
            name='Descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
