# Generated by Django 3.1.3 on 2024-09-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0009_vivienda_tiporecaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptosfacturados',
            name='Basico',
            field=models.IntegerField(null=True),
        ),
    ]
