# Generated by Django 3.0.5 on 2020-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0010_medidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='Direccion',
            field=models.CharField(choices=[('Pasonivel Viejo', 'Sector pasonivel viejo'), ('Pasonivel Destapada', 'Sector pasonivel destapada'), ('Caimalito Centro', 'Sector caimalito centro'), ('Barrio Nuevo', 'Sector barrio nuevo'), ('20 de julio', 'Sector 20 de julio')], max_length=20),
        ),
    ]
