# Generated by Django 3.1.3 on 2024-04-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0010_consumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumos',
            name='Consumo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumos',
            name='Lecturaactual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumos',
            name='Lecturaanterior',
            field=models.IntegerField(),
        ),
    ]
