# Generated by Django 3.1.3 on 2024-04-26 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0010_auto_20240426_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdospago',
            name='FechaExpe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
