# Generated by Django 3.1.3 on 2022-12-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0010_auto_20221208_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NovedadPropietario',
        ),
    ]
