# Generated by Django 3.1.3 on 2024-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0010_conceptosfacturados_basico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumosmensual',
            name='promedio',
            field=models.IntegerField(),
        ),
    ]
