# Generated by Django 3.1.3 on 2024-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0011_auto_20240402_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumos',
            name='ano',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumos',
            name='mes',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
