# Generated by Django 3.1.3 on 2024-12-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0011_auto_20241215_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectores',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
    ]
