# Generated by Django 3.1.3 on 2024-04-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0011_acuerdospago_fechaexpe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='FechaLimite',
        ),
    ]
