# Generated by Django 3.0.5 on 2020-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0012_auto_20200702_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='MatriculaAnt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
