# Generated by Django 3.1.3 on 2024-04-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0012_remove_facturas_fechalimite'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='FechaLimite',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
