# Generated by Django 3.1.3 on 2025-01-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0012_auto_20241218_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='CantPredios',
            field=models.CharField(choices=[('1', '1 - predio'), ('2', '2 - predios'), ('3', '3 - predios'), ('4', '4 - predios'), ('5', '5 - predios')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Ciclo',
            field=models.CharField(choices=[('1', 'Conduccion'), ('2', 'Pasonivel viejo'), ('3', 'Barrio nuevo'), ('4', 'Caimalito via principal 1'), ('5', '20 julio'), ('6', 'Carbonera'), ('7', 'Caimalito via principal 2')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Diametro',
            field=models.CharField(choices=[('1/2', '1/2'), ('3/4', '3/4'), ('1', '1'), ('1-1/2', '1-1/2')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('Instalacion', 'Instalacion')], default='Instalacion', max_length=60),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='MatriculaAnt',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='TipoInstalacion',
            field=models.CharField(choices=[('Residencial', 'Residencial (Res)'), ('Comercial', 'Comercial (Com)'), ('Industrial', 'Industrial (Ind)'), ('Oficial', 'Oficial (Ofi)')], default='Res', max_length=60),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='TipoRecaudo',
            field=models.CharField(choices=[('Aporte fijo', 'Aporte fijo'), ('Especial', 'Especial'), ('Mantenimiento', 'Mantenimiento'), ('Industrial', 'Industrial'), ('Oficial', 'Oficial'), ('Comercial', 'Comercial')], default='Aporte fijo', max_length=20, null=True),
        ),
    ]
