# Generated by Django 3.1.3 on 2024-04-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0012_auto_20240402_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifa',
            old_name='bifamiliar',
            new_name='comercial',
        ),
        migrations.RenameField(
            model_name='tarifa',
            old_name='multifamiliar',
            new_name='industrial',
        ),
        migrations.AddField(
            model_name='tarifa',
            name='oficial',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='valormetro',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
