# Generated by Django 3.1.3 on 2022-12-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0012_delete_proveedores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionExterna',
        ),
    ]
