# Generated by Django 3.1.3 on 2024-04-27 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0013_facturas_fechalimite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasConceptos',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('IdConcepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.conceptosfacturados')),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.facturas')),
            ],
        ),
    ]
