# Generated by Django 3.1.3 on 2022-12-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0013_delete_asignacionexterna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivos',
        ),
    ]
