# Generated by Django 3.1.3 on 2025-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0013_auto_20250112_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='Subsidio',
            field=models.CharField(choices=[('1/2', '1/2'), ('3/4', '3/4'), ('1', '1'), ('1-1/2', '1-1/2')], default='No', max_length=20, null=True),
        ),
    ]
