# Generated by Django 3.0.5 on 2020-07-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0013_auto_20200702_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='Piso',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
