# Generated by Django 3.1.3 on 2024-04-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0013_auto_20240414_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conceptos',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=350, null=True)),
                ('Observacion', models.CharField(max_length=350, null=True)),
                ('Estado', models.CharField(max_length=350, null=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Valor', models.IntegerField(null=True)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Concepto de cobro',
                'verbose_name_plural': 'Conceptos de cobro',
            },
        ),
    ]
