# Generated by Django 3.1.3 on 2025-04-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0014_vivienda_subsidio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaspqrs',
            name='Descripcion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Subsidio',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=20, null=True),
        ),
    ]
