# Generated by Django 3.1.3 on 2024-04-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0014_facturasconceptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='IdFactura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
