# Generated by Django 3.1.3 on 2022-12-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0014_delete_archivos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivosAcueducto',
        ),
    ]
