# Generated by Django 3.0.5 on 2020-07-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0014_auto_20200702_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='CantHabitantes',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='MatriculaAnt',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Piso',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='ProfAcometida',
            field=models.CharField(max_length=4),
        ),
    ]
