# Generated by Django 3.1.3 on 2024-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0014_conceptos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptosFacturados',
            fields=[
                ('IdRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('AporteFijo', models.IntegerField(null=True)),
                ('CuotaMatricula', models.IntegerField(null=True)),
                ('Suspencion', models.IntegerField(null=True)),
                ('Reconexion', models.IntegerField(null=True)),
                ('AcuerdoPago', models.IntegerField(null=True)),
                ('Subsidio', models.IntegerField(null=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Total', models.IntegerField(null=True)),
                ('Estado', models.CharField(max_length=10, null=True)),
                ('Periodo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Concepto de cobro',
                'verbose_name_plural': 'Conceptos de cobro',
            },
        ),
    ]
