# Generated by Django 3.1.3 on 2025-04-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0015_auto_20250402_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='sectores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAL.sectores'),
        ),
    ]
