# Generated by Django 3.1.3 on 2023-01-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0015_delete_archivosacueducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='Potipo1',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='Potipo2',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='consumomin',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='consumotipo1',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='consumotipo2',
        ),
    ]
