# Generated by Django 3.0.5 on 2020-07-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0015_auto_20200702_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('Operativo', 'Operativo (OP)'), ('Suspendido', 'Suspendido (SP)'), ('Retirado', 'Retirado  (RD)'), ('En contruccion', 'En Contruccion (EC)')], default='EC', max_length=60),
        ),
        migrations.CreateModel(
            name='CobroMatricula',
            fields=[
                ('IdCobroM', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=10)),
                ('Valor', models.CharField(max_length=8)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda')),
            ],
            options={
                'verbose_name': 'Cobro matricula',
                'verbose_name_plural': 'Cobro matriculas',
            },
        ),
    ]
