# Generated by Django 3.1.3 on 2024-05-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0015_auto_20240426_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptosfacturados',
            old_name='Otroscobros',
            new_name='SaldoAnterior',
        ),
    ]
