# Generated by Django 3.1.3 on 2024-04-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0015_conceptosfacturados'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptosfacturados',
            name='IdVivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda'),
            preserve_default=False,
        ),
    ]
