# Generated by Django 3.1.3 on 2023-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0016_auto_20230116_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='bifamiliar',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='especial',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='multifamiliar',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='Mantenimiento',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='Recargo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='TarifaReconexion',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='TarifaSuspencion',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='Valor',
            field=models.CharField(max_length=5),
        ),
    ]
