# Generated by Django 3.0.5 on 2020-07-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0016_auto_20200704_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobromatricula',
            name='Estado',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
