# Generated by Django 3.1.3 on 2025-04-03 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0016_vivienda_sectores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclos',
            fields=[
                ('IdCiclo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
                ('idacueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto')),
            ],
            options={
                'verbose_name': 'Listado de sectores',
                'verbose_name_plural': 'Lista de sectores',
            },
        ),
    ]
