# Generated by Django 3.0.5 on 2020-07-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0017_cobromatricula_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobromatricula',
            name='Descripcion',
            field=models.CharField(max_length=20),
        ),
    ]
