# Generated by Django 3.1.3 on 2023-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0017_auto_20230116_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='FechaFinal',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='FechaInicial',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
