# Generated by Django 3.1.3 on 2025-04-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0017_ciclos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='ciclos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAL.ciclos'),
        ),
    ]
