# Generated by Django 3.1.3 on 2025-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0018_vivienda_ciclos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclos',
            name='Diametro',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciclos',
            name='Tipo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
