# Generated by Django 3.1.3 on 2023-01-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0018_auto_20230116_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='CantPredios',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='InfoInstalacion',
            field=models.CharField(choices=[('Unifamiliar', 'Unifamiliar'), ('Bifamiliar', 'Bifamiliar'), ('Multifamiliar', 'Multifamiliar'), ('Comercial', 'Comercial'), ('Especial', 'Especial'), ('Agricola', 'Agricola')], max_length=30),
        ),
    ]
