# Generated by Django 3.0.5 on 2020-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0018_auto_20200704_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='Ano',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
