# Generated by Django 3.1.3 on 2025-04-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0019_auto_20250402_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionBloque',
        ),
    ]
