# Generated by Django 3.0.5 on 2020-07-04 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0019_ciclo_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='Ano',
        ),
    ]
