# Generated by Django 3.1.3 on 2023-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0019_auto_20230116_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionBloque',
            fields=[
                ('IdBloque', models.AutoField(primary_key=True, serialize=False)),
                ('Bloque', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=150)),
                ('Estada', models.CharField(max_length=150)),
                ('Fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
            },
        ),
        migrations.AlterModelOptions(
            name='novedadessistema',
            options={'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.AlterField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='Descripcion',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='Nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='TipoSolicitud',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Solicitud', 'Solicitud')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='CantPredios',
            field=models.CharField(choices=[('1', '1 - predio'), ('2', '2 - predios'), ('3', '3 - predios'), ('4', '4 - predios'), ('5', '5 - predios')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Direccion',
            field=models.CharField(choices=[('Pasonivel Viejo', 'Sector pasonivel viejo'), ('Pasonivel Destapada', 'Sector pasonivel destapada'), ('Caimalito Centro', 'Sector caimalito centro'), ('Barrio Nuevo', 'Sector barrio nuevo'), ('20 de julio', 'Sector 20 de julio'), ('Hacienda', 'Hacienda')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='InfoInstalacion',
            field=models.CharField(choices=[('Unifamiliar', 'Unifamiliar'), ('Bifamiliar', 'Bifamiliar'), ('Multifamiliar', 'Multifamiliar'), ('Especial', 'Especial')], max_length=30),
        ),
    ]
