# Generated by Django 3.1.3 on 2023-06-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0020_auto_20230611_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionbloque',
            old_name='Estada',
            new_name='Estado',
        ),
    ]
