# Generated by Django 3.1.3 on 2025-04-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0020_delete_asignacionbloque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CobroMatricula',
        ),
    ]
