# Generated by Django 3.0.5 on 2020-07-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0020_remove_ciclo_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='ano',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
