# Generated by Django 3.1.3 on 2023-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0021_auto_20230611_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionbloque',
            name='Estadocuenta',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
