# Generated by Django 3.0.5 on 2020-07-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0021_estadocuenta_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGastos',
            fields=[
                ('IdSoGa', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=300)),
                ('TipoSolicitud', models.CharField(max_length=20)),
                ('Valor', models.CharField(max_length=10)),
                ('Estado', models.CharField(max_length=15)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('AreaResponsable', models.CharField(max_length=15)),
                ('Soporte', models.FileField(upload_to='SoporteGastos/')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de gasto',
                'verbose_name_plural': 'solicitudes de gastos',
            },
        ),
    ]
