# Generated by Django 3.0.5 on 2020-07-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0022_solicitudgastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='TipoSolicitud',
            field=models.CharField(choices=[('Pago Nomina', 'Pago Nomina'), ('Biaticos viaje', 'Biaticos viajea'), ('Elementos area tecnica', 'Mantenimiento redes'), ('Servicios publicos', 'Servicios publicos'), ('Gastos varios', 'Gastos varios')], max_length=50),
        ),
    ]
