# Generated by Django 3.1.3 on 2023-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0022_asignacionbloque_estadocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('IdProvedor', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Nombrecompleto', models.CharField(max_length=100)),
                ('Personeria', models.CharField(choices=[('Persona natural', 'Persona natural'), ('Personeria juridica', 'Personeria juridica')], max_length=100, null=True)),
                ('Direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('Representantelegal', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Direccion',
            field=models.CharField(choices=[('Pasonivel Viejo', 'Sector pasonivel viejo'), ('Pasonivel Destapada', 'Sector pasonivel destapada'), ('Caimalito Centro', 'Sector caimalito centro'), ('Barrio Nuevo', 'Sector barrio nuevo'), ('20 de julio', 'Sector 20 de julio'), ('Hacienda', 'Hacienda'), ('Carbonera', 'Carbonera')], max_length=20),
        ),
    ]
