# Generated by Django 3.0.5 on 2020-07-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0023_auto_20200720_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='TipoSolicitud',
            field=models.CharField(max_length=50),
        ),
    ]
