# Generated by Django 3.1.3 on 2024-05-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0023_auto_20240524_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='IdAcueducto',
            field=models.ForeignKey(default=900017239, on_delete=django.db.models.deletion.CASCADE, to='SAAL.acueducto'),
            preserve_default=False,
        ),
    ]
