# Generated by Django 3.1.3 on 2023-07-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0023_auto_20230723_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('IdCredito', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ValorInicial', models.CharField(max_length=40)),
                ('CantCuotas', models.CharField(max_length=3)),
                ('CantPendientes', models.CharField(max_length=3)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('IdProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.proveedor')),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
            },
        ),
    ]
