# Generated by Django 3.1.3 on 2024-05-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0024_asignacion_idacueducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acueducto',
            name='logo',
            field=models.ImageField(upload_to='usuarios'),
        ),
    ]
