# Generated by Django 3.1.3 on 2023-07-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0024_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='CantPendientes',
        ),
    ]
