# Generated by Django 3.0.5 on 2020-07-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0024_auto_20200723_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionExterna',
            fields=[
                ('IdAsigExt', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=10)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Soporte', models.FileField(upload_to='AsignacionExterna/')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto externo',
                'verbose_name_plural': 'Asignacion de presupuesto externo',
            },
        ),
    ]
