# Generated by Django 3.1.3 on 2023-07-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0025_remove_credito_cantpendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='Estado',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
