# Generated by Django 3.0.5 on 2020-07-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0025_asignacionexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionexterna',
            name='Fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
