# Generated by Django 3.0.5 on 2020-07-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0026_asignacionexterna_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acueducto',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
    ]
