# Generated by Django 3.1.3 on 2023-07-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0026_credito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='NombreCredito',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
