# Generated by Django 3.1.3 on 2023-07-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0027_credito_nombrecredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='Estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Pagado', 'Pagado')], max_length=10),
        ),
    ]
