# Generated by Django 3.0.5 on 2020-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0027_auto_20200730_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='Estado',
            field=models.CharField(choices=[('Anulada', 'Anular solicitud'), ('Aprobada', 'Aprobar solicitud')], max_length=15),
        ),
    ]
