# Generated by Django 3.0.5 on 2020-08-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0028_auto_20200804_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='Piso',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
