# Generated by Django 3.1.3 on 2023-07-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0028_auto_20230723_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='IdCredito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
