# Generated by Django 3.1.3 on 2023-07-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0029_auto_20230723_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='CuotasPendiente',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito',
            name='ValorPendiente',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
