# Generated by Django 3.0.5 on 2020-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0029_auto_20200814_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaciones',
            name='Descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='Estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('No certificada', 'No certificada'), ('Certificada', 'Certificada')], max_length=25),
        ),
    ]
