# Generated by Django 3.1.3 on 2024-06-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0030_credito_idacueducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Cargo',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Operario', 'Operario)'), ('Secretario/a', 'Secretario/a'), ('Tesorero/a', 'Tesorero/a'), ('Auxiliar', 'Auxiliar')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Departamento',
            field=models.CharField(choices=[('Area administrativa', 'Area administrativa'), ('Area operativa', 'Area operativa)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(choices=[('Nivel 1', 'Nivel 1'), ('Nivel 2', 'Nivel 2)'), ('Nivel 3', 'Nivel 3')], max_length=100, null=True),
        ),
    ]
