# Generated by Django 3.0.5 on 2020-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0030_auto_20200825_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='Estado',
            field=models.CharField(choices=[('No certificada', 'No certificada'), ('Certificada', 'Certificada')], max_length=25),
        ),
    ]
