# Generated by Django 3.1.3 on 2023-07-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0030_auto_20230725_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='Representantelegal',
        ),
    ]
