# Generated by Django 3.1.3 on 2024-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0031_auto_20240601_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='IdUsuario',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(choices=[('Nivel 1', 'Nivel 1'), ('Nivel 2', 'Nivel 2'), ('Nivel 3', 'Nivel 3')], max_length=100, null=True),
        ),
    ]
