# Generated by Django 3.1.3 on 2023-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0031_remove_proveedor_representantelegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudgastos',
            name='proveedor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
