# Generated by Django 3.0.5 on 2020-08-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0031_auto_20200826_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='NombreEmpresa',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='certificaciones',
            name='Soporte',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Piso',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
