# Generated by Django 3.0.5 on 2020-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0032_auto_20200826_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='NombreEmpresa',
            field=models.CharField(max_length=300),
        ),
    ]
