# Generated by Django 3.1.3 on 2023-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0032_solicitudgastos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='AreaResponsable',
            field=models.CharField(choices=[('Gerencia', 'Gerencia'), ('Secretaria general', 'Secretaria general'), ('Control interno', 'Control interno'), ('Subgerencia tecnica', 'Subgerencia tecnica'), ('Subgerencia operaciones', 'Subgerencia operaciones'), ('Subgerencia comercial', 'Subgerencia comercial'), ('Subgerencia financiera y administrativa', 'Subgerencia financiera y administrativa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudgastos',
            name='TipoSolicitud',
            field=models.CharField(choices=[('Servicios publicos', 'Pago - servicios publicos'), ('Nomina', 'Pago - nomina'), ('Viaticos', 'Pago - viaticos'), ('Impuestos', 'Pago - impuestos'), ('Mantenimiento infrastructura', 'Pago - Mantenimiento de infraestructura'), ('Transporte', 'Pago - transporte'), ('Documentacion', 'Subgerencia financiera y administrativa')], max_length=50),
        ),
    ]
