# Generated by Django 3.1.3 on 2024-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0032_auto_20240601_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('IdSector', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Listado de sectores',
                'verbose_name_plural': 'Lista de sectores',
            },
        ),
    ]
