# Generated by Django 3.0.5 on 2020-09-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAAL', '0033_auto_20200826_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirCerti',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('IdCertificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Certificaciones')),
                ('Usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'confirmacion',
                'verbose_name_plural': 'listado de confirmaciones',
            },
        ),
    ]
