# Generated by Django 3.1.3 on 2023-09-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0033_auto_20230815_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='TipoSolicitud',
            field=models.CharField(choices=[('Servicios publicos', 'Pago - servicios publicos'), ('Nomina', 'Pago - nomina'), ('Viaticos', 'Pago - viaticos'), ('Impuestos', 'Pago - impuestos'), ('Mantenimiento infrastructura', 'Pago - Mantenimiento de infraestructura'), ('Transporte', 'Pago - transporte')], max_length=50),
        ),
    ]
