# Generated by Django 3.1.3 on 2023-12-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0034_auto_20230922_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaFacturas',
            fields=[
                ('IdDescarga', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.factura')),
            ],
            options={
                'verbose_name': 'Descarga',
                'verbose_name_plural': 'Descargas',
            },
        ),
    ]
