# Generated by Django 3.0.5 on 2020-09-01 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAAL', '0034_confircerti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confircerti',
            name='Usuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
