# Generated by Django 3.0.5 on 2020-09-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0035_auto_20200901_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confircerti',
            old_name='Usuid',
            new_name='usuid',
        ),
    ]
