# Generated by Django 3.1.3 on 2024-01-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0035_descargafacturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadesRetiro',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Novedad de retiro',
                'verbose_name_plural': 'Novedades de retiro',
            },
        ),
    ]
