# Generated by Django 3.0.5 on 2020-09-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0036_auto_20200901_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='Soporte',
            field=models.FileField(null=True, upload_to='documentos/'),
        ),
    ]
