# Generated by Django 3.1.3 on 2024-03-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0036_novedadesretiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='acueducto',
            name='Sigla',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
