# Generated by Django 3.0.5 on 2020-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0037_auto_20200901_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='Soporte',
            field=models.FileField(default=1, upload_to='documentos/'),
            preserve_default=False,
        ),
    ]
