# Generated by Django 3.1.3 on 2024-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0037_acueducto_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='m3',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
