# Generated by Django 3.1.3 on 2024-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0038_tarifa_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='IdTarifa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
