# Generated by Django 3.1.3 on 2024-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0039_auto_20240329_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Presidente', 'Presidente'), ('Vicepresidente', 'Vicepresidente'), ('Operario', 'Operario)'), ('Secretario/a', 'Secretario/a'), ('Tesorero', 'Tesorero'), ('Auxiliar', 'Auxiliar'), ('Administrador de sistemas', 'Administrador de sistemas(Dir)')], default='Auxiliar', max_length=100, null=True),
        ),
    ]
