# Generated by Django 3.0.5 on 2020-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0039_auto_20200901_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='Soporte',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
