# Generated by Django 3.0.5 on 2020-09-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0040_auto_20200901_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='Soporte',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
    ]
