# Generated by Django 3.1.3 on 2024-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0040_auto_20240329_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidores',
            name='LecturaInicial',
        ),
        migrations.AddField(
            model_name='medidores',
            name='Certificado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidores',
            name='Designacion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidores',
            name='Diametronominal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidores',
            name='Modelo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidores',
            name='clase',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medidores',
            name='Marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medidores',
            name='Tipo',
            field=models.CharField(max_length=50),
        ),
    ]
