# Generated by Django 3.1.3 on 2024-03-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0041_auto_20240329_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidores',
            name='Fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
