# Generated by Django 3.0.5 on 2020-09-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0041_auto_20200901_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confircerti',
            name='usuid',
        ),
        migrations.AddField(
            model_name='confircerti',
            name='IdUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario'),
            preserve_default=False,
        ),
    ]
