# Generated by Django 3.0.5 on 2020-09-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0042_auto_20200903_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorMatricula',
            fields=[
                ('IdValor', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=10)),
                ('Fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'valor matricula',
                'verbose_name_plural': 'listado de valor de matricula',
            },
        ),
        migrations.RemoveField(
            model_name='cobromatricula',
            name='Valor',
        ),
        migrations.AddField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobromatricula',
            name='IdValor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.ValorMatricula'),
            preserve_default=False,
        ),
    ]
