# Generated by Django 3.0.5 on 2020-09-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0043_auto_20200903_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(choices=[('Contado', 'Contado'), ('2', '2'), ('4', '4'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36')], max_length=10),
        ),
    ]
