# Generated by Django 3.1.3 on 2024-03-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0043_auto_20240329_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confircerti',
            name='IdCertificacion',
        ),
        migrations.RemoveField(
            model_name='confircerti',
            name='IdUsuario',
        ),
        migrations.DeleteModel(
            name='Certificaciones',
        ),
        migrations.DeleteModel(
            name='ConfirCerti',
        ),
    ]
