# Generated by Django 3.0.5 on 2020-09-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0044_auto_20200908_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36')], max_length=10),
        ),
    ]
