# Generated by Django 3.0.5 on 2020-09-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0045_auto_20200911_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('IdPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('TipoPermiso', models.CharField(max_length=10)),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto externo',
                'verbose_name_plural': 'Asignacion de presupuesto externo',
            },
        ),
    ]
