# Generated by Django 3.0.5 on 2020-09-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0046_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso'), ('RE', 'Registro'), ('El', 'Eliminacion'), ('MO', 'Modificar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='total',
            name='IdEstadoCuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAL.EstadoCuenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Presidente', 'Presidente (Pdte)'), ('Cartera', 'Cartera (Ct)'), ('Operario', 'Operario (Ope)'), ('Auxiliar', 'Auxiliar (Aux)')], default='Consultor', max_length=100, null=True),
        ),
    ]
