# Generated by Django 3.0.5 on 2020-09-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0047_auto_20200928_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='IdCobroM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAL.CobroMatricula'),
        ),
    ]
