# Generated by Django 3.0.5 on 2020-10-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0048_total_idcobrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('IdPqrs', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=1000, null=True)),
                ('FechaRadicado', models.DateTimeField(auto_now_add=True)),
                ('Soporte', models.FileField(null=True, upload_to='pqrs/')),
                ('CedulaNit', models.CharField(max_length=15, null=True)),
                ('NombreCompleto', models.CharField(max_length=100, null=True)),
                ('Telefono', models.CharField(max_length=10, null=True)),
                ('Correo', models.EmailField(max_length=60, null=True)),
                ('Direccion', models.CharField(max_length=200, null=True)),
                ('TipoSolicitud', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Pqrs',
                'verbose_name_plural': 'Pqr',
            },
        ),
    ]
