# Generated by Django 3.0.5 on 2020-10-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0049_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='Estado',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
