# Generated by Django 3.0.5 on 2020-10-26 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAAL', '0050_pqrs_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='usuid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
