# Generated by Django 3.0.5 on 2020-10-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0051_pqrs_usuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='Anonimo',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
