# Generated by Django 3.0.5 on 2020-10-27 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0052_pqrs_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='usuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario'),
        ),
    ]
