# Generated by Django 3.0.5 on 2020-10-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0053_auto_20201026_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestasPqrs',
            fields=[
                ('IdRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('Soporte', models.FileField(null=True, upload_to='')),
                ('IdPqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Pqrs')),
            ],
            options={
                'verbose_name': 'Respuestas',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
