# Generated by Django 3.0.5 on 2020-11-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0054_respuestaspqrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaspqrs',
            name='Soporte',
            field=models.FileField(null=True, upload_to='respuestaspqr/'),
        ),
    ]
