# Generated by Django 3.0.5 on 2020-11-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0055_auto_20201104_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='Estado',
            field=models.CharField(choices=[('Cerrada', 'Cerrada')], max_length=40),
        ),
    ]
