# Generated by Django 3.0.5 on 2020-11-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0056_auto_20201109_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='IdCobroM',
        ),
    ]
