# Generated by Django 3.0.5 on 2020-11-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0057_remove_total_idcobrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocuenta',
            name='IdCiclo',
        ),
    ]
