# Generated by Django 3.0.5 on 2020-11-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0058_remove_estadocuenta_idciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocuenta',
            name='ano',
        ),
    ]
