# Generated by Django 3.0.5 on 2020-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0059_remove_estadocuenta_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='FechaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
