# Generated by Django 3.0.5 on 2020-11-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0060_estadocuenta_fechaactualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocuenta',
            name='Estado',
        ),
    ]
