# Generated by Django 3.0.5 on 2020-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0061_remove_estadocuenta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='Estado',
            field=models.CharField(default='SIN PAGAR', max_length=100),
            preserve_default=False,
        ),
    ]
