# Generated by Django 3.0.5 on 2020-11-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0062_estadocuenta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='Ciclo',
            field=models.CharField(choices=[('Ciclo 2', 'Troncal pasonivel viejo'), ('Ciclo 3', 'Troncal caimalito via principal'), ('Ciclo 4', 'Troncal Barrio nuevo'), ('Ciclo 5', 'Linea Auxiliar 20 julio')], max_length=40),
        ),
    ]
