# Generated by Django 3.0.5 on 2020-11-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0063_auto_20201114_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='IdCiclo',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Ciclo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='IdEstadoCuenta',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='SAAL.EstadoCuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Ciclo',
            field=models.CharField(choices=[('Ciclo 2', 'Troncal pasonivel viejo'), ('Ciclo 4', 'Troncal caimalito via principal'), ('Ciclo 3', 'Troncal Barrio nuevo'), ('Ciclo 5', 'Linea Auxiliar 20 julio')], max_length=40),
        ),
    ]
