# Generated by Django 3.0.5 on 2020-11-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0064_auto_20201115_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='FechaFin',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='FechaIni',
        ),
    ]
