# Generated by Django 3.0.5 on 2020-11-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0065_auto_20201115_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='Descripcion',
            field=models.CharField(default='cobro por consumo', max_length=100),
            preserve_default=False,
        ),
    ]
