# Generated by Django 3.0.5 on 2020-11-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0066_estadocuenta_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
