# Generated by Django 3.0.5 on 2020-11-19 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SAAL', '0067_delete_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('IdPago', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPago', models.DateTimeField(auto_now_add=True)),
                ('Ano', models.CharField(max_length=4)),
                ('ValorPago', models.CharField(max_length=10)),
                ('Efectivo', models.CharField(max_length=10)),
                ('Devuelta', models.CharField(max_length=10)),
                ('IdFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Factura')),
                ('Usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuestas',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
