# Generated by Django 3.0.5 on 2020-11-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0068_pagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='Usuid',
        ),
        migrations.AddField(
            model_name='pagos',
            name='IdUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario'),
            preserve_default=False,
        ),
    ]
