# Generated by Django 3.0.5 on 2020-11-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0069_auto_20201119_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='IdVivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda'),
            preserve_default=False,
        ),
    ]
