# Generated by Django 3.0.5 on 2020-11-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0070_pagos_idvivienda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.CreateModel(
            name='OrdenesSuspencion',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Deuda', models.CharField(max_length=10)),
                ('FechaExpe', models.DateTimeField(auto_now_add=True)),
                ('FechaEjecucion', models.CharField(max_length=40)),
                ('Generado', models.CharField(max_length=5)),
                ('UsuarioEjecuta', models.CharField(max_length=5)),
                ('IdEstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.EstadoCuenta')),
            ],
            options={
                'verbose_name': 'Orden de suspencion',
                'verbose_name_plural': 'Ordenes de suspencion',
            },
        ),
    ]
