# Generated by Django 3.0.5 on 2020-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0071_auto_20201119_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenessuspencion',
            name='Estado',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
