# Generated by Django 3.0.5 on 2020-11-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0072_ordenessuspencion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedadvivienda',
            name='IdAcueducto',
        ),
    ]
