# Generated by Django 3.0.5 on 2020-11-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0073_remove_novedadvivienda_idacueducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadvivienda',
            name='usuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario'),
        ),
    ]
