# Generated by Django 3.0.5 on 2020-11-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0074_auto_20201119_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadvivienda',
            name='EstadoCuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.EstadoCuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novedadvivienda',
            name='Valor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
