# Generated by Django 3.0.5 on 2020-11-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0075_auto_20201120_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesReconexion',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Deuda', models.CharField(max_length=10)),
                ('FechaExpe', models.DateTimeField(auto_now_add=True)),
                ('FechaEjecucion', models.CharField(max_length=40)),
                ('Generado', models.CharField(max_length=5)),
                ('Estado', models.CharField(max_length=40)),
                ('UsuarioEjecuta', models.CharField(max_length=5)),
                ('IdEstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.EstadoCuenta')),
            ],
            options={
                'verbose_name': 'Orden de Reconexion',
                'verbose_name_plural': 'Ordenes de Reconexion',
            },
        ),
    ]
