# Generated by Django 3.0.5 on 2020-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0076_ordenesreconexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenessuspencion',
            name='Generado',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ordenessuspencion',
            name='UsuarioEjecuta',
            field=models.CharField(max_length=100),
        ),
    ]
