# Generated by Django 3.0.5 on 2020-11-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0077_auto_20201124_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesreconexion',
            name='Generado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenesreconexion',
            name='UsuarioEjecuta',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Ciclo',
            field=models.CharField(choices=[('2', 'Ciclo pasonivel viejo'), ('3', 'Ciclo Barrio nuevo'), ('4', 'Ciclo caimalito via principal'), ('5', 'Ciclo Auxiliar 20 julio')], max_length=40),
        ),
    ]
