# Generated by Django 3.0.5 on 2020-11-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0078_auto_20201126_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='IdPropietario',
        ),
        migrations.AddField(
            model_name='archivos',
            name='IdVivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Vivienda'),
            preserve_default=False,
        ),
    ]
