# Generated by Django 3.0.5 on 2020-11-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0079_auto_20201129_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosAcueducto',
            fields=[
                ('IdArchivo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreArchivo', models.CharField(max_length=100, null=True)),
                ('Archivo', models.FileField(null=True, upload_to='archivos/')),
                ('IdAcueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.Acueducto')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
