# Generated by Django 3.0.5 on 2020-11-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0080_archivosacueducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosacueducto',
            name='Carpeta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
