# Generated by Django 3.0.5 on 2020-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0081_archivosacueducto_carpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='Carpeta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivos',
            name='FechaSubida',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='archivosacueducto',
            name='FechaSubida',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
