# Generated by Django 3.0.5 on 2020-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0082_auto_20201201_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='Archivo',
            field=models.FileField(null=True, upload_to='documentosusuarios/'),
        ),
    ]
