# Generated by Django 3.0.5 on 2020-12-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0083_auto_20201201_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='usuid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='SAAL.Usuario'),
            preserve_default=False,
        ),
    ]
