# Generated by Django 3.0.5 on 2020-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0084_archivos_usuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierres',
            fields=[
                ('IdCierre', models.AutoField(primary_key=True, serialize=False)),
                ('Ingresos', models.CharField(max_length=100)),
                ('Gastos', models.CharField(max_length=100)),
                ('Presupuesto', models.CharField(max_length=100)),
                ('Ciclo', models.CharField(max_length=100)),
                ('Ano', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cierre mensual',
                'verbose_name_plural': 'Lista de cierres mensuales',
            },
        ),
    ]
