# Generated by Django 3.0.5 on 2020-12-04 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0085_cierres'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierres',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
