# Generated by Django 3.0.5 on 2020-12-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0086_cierres_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierres',
            name='Ano',
            field=models.CharField(max_length=100),
        ),
    ]
