# Generated by Django 3.0.5 on 2020-12-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0087_auto_20201204_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierres',
            name='NoRecaudo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
