# Generated by Django 3.0.5 on 2020-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0088_cierres_norecaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierres',
            name='Recaudado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
