# Generated by Django 3.0.5 on 2020-12-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0090_cobromatricula_cuotaspendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='TotalConsumo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
