# Generated by Django 3.0.5 on 2020-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0091_factura_totalconsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobromatricula',
            name='ValorPendiente',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
