# Generated by Django 3.0.5 on 2020-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0092_cobromatricula_valorpendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='InfoInstalacion',
            field=models.CharField(choices=[('Instalacion Empotrada', 'Instalacion Empotrada'), ('Instalacion a la vista', 'Instalacion a la vista'), ('Instalacion Mixta', 'Instalacion Mixta')], max_length=30),
        ),
    ]
