# Generated by Django 3.0.5 on 2020-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0093_auto_20201211_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobromatricula',
            name='Cuota',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
