# Generated by Django 3.0.5 on 2020-12-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0094_cobromatricula_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='OtrosCobros',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
