# Generated by Django 3.0.5 on 2020-12-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0095_factura_otroscobros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenessuspencion',
            name='FechaEjecucion',
            field=models.DateTimeField(),
        ),
    ]
