# Generated by Django 3.0.5 on 2021-01-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0096_auto_20201211_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobromatricula',
            name='CantCuotas',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Presidente', 'Presidente (Pdte)'), ('Cartera', 'Cartera (Ct)'), ('Operario', 'Operario (Ope)'), ('Auxiliar', 'Auxiliar (Aux)'), ('Sistemas', 'Sistemas (Sis)')], default='Auxiliar', max_length=100, null=True),
        ),
    ]
