# Generated by Django 3.0.5 on 2021-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0097_auto_20210105_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadesGenerales',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250)),
                ('TipoNovedad', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Novedad general',
                'verbose_name_plural': 'Novedades generales',
            },
        ),
    ]
