# Generated by Django 3.0.5 on 2021-01-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0098_novedadesgenerales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesreconexion',
            name='FechaEjecucion',
            field=models.DateTimeField(),
        ),
    ]
