# Generated by Django 3.0.5 on 2021-01-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0099_auto_20210109_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso'), ('RE', 'Registro'), ('El', 'Eliminacion'), ('MO', 'Modificar'), ('NOAC', 'No acceso')], max_length=10),
        ),
    ]
