# Generated by Django 3.0.5 on 2021-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0100_auto_20210109_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso'), ('NOAC', 'No acceso - CONTROL PRESUPUESTAL'), ('NOACP', 'No acceso - PQRS')], max_length=10),
        ),
    ]
