# Generated by Django 3.0.5 on 2021-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0101_auto_20210109_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso'), ('NOAC', 'No acceso - CONTROL PRESUPUESTAL'), ('NOACFA', 'No acceso - FACTURACION'), ('NOACRE', 'No acceso - REPORTES'), ('NOACP', 'No acceso - PQRS'), ('NOACSR', 'No acceso - SUSPENCIONES/RECONEXIONES')], max_length=10),
        ),
    ]
