# Generated by Django 3.0.5 on 2021-01-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0104_auto_20210109_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acueducto',
            name='Mapa',
        ),
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso'), ('NOACCE', 'No acceso - CAMBIO ESTADO'), ('NOAC', 'No acceso - CONTROL PRESUPUESTAL'), ('NOACFA', 'No acceso - FACTURACION'), ('NOACRE', 'No acceso - REPORTES'), ('NOACP', 'No acceso - PQRS'), ('NOACSR', 'No acceso - SUSPENCIONES/RECONEXIONES'), ('NOACLT', 'No acceso - LISTA TITULARES'), ('NOACLP', 'No acceso - LISTA PREDIOS'), ('NOACBU', 'No acceso - BUSQUEDAS'), ('NOACRT', 'No acceso - REGISTRO TITULAR'), ('NOACRP', 'No acceso - REGISTRO PREDIO'), ('NOACRPQ', 'No acceso - REGISTRO PQRS'), ('NOACRPG', 'No acceso - REGISTRO PAGO'), ('NOACMT', 'No acceso - MODIFICAR TITULAR'), ('NOACMP', 'No acceso - MODIFICAR PREDIO'), ('NOACCT', 'No acceso - CAMBIAR TITULAR'), ('NOACMAPA', 'No acceso - CAMBIAR TITULAR')], max_length=10),
        ),
    ]
