# Generated by Django 3.1.3 on 2021-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0106_auto_20210113_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Presidente', 'Presidente (Pdte)'), ('Cartera', 'Cartera (Ct)'), ('Operario', 'Operario (Ope)'), ('Auxiliar', 'Auxiliar (Aux)'), ('Sistemas', 'Administrador de Sistemas (Sis)')], default='Auxiliar', max_length=100, null=True),
        ),
    ]
