# Generated by Django 3.1.3 on 2021-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0107_auto_20210121_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='MatriculaAnt',
            field=models.CharField(max_length=4),
        ),
    ]
