# Generated by Django 3.1.3 on 2021-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0108_auto_20210201_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadesgenerales',
            name='Descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='novedadpropietario',
            name='Descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='novedadvivienda',
            name='Descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='Descripcion',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudgastos',
            name='Descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('Operativo', 'Operativo (OP)'), ('Suspendido', 'Suspendido (SP)'), ('Mantenimiento', 'Mantenimiento (MT)'), ('Retirado', 'Retirado  (RD)'), ('En contruccion', 'En Contruccion (EC)')], default='EC', max_length=60),
        ),
    ]
