# Generated by Django 3.1.3 on 2021-02-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0109_auto_20210216_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgastos',
            name='AreaResponsable',
            field=models.CharField(max_length=100),
        ),
    ]
