# Generated by Django 3.1.3 on 2021-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0110_auto_20210225_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='Valor',
            field=models.CharField(max_length=15),
        ),
    ]
