# Generated by Django 3.1.3 on 2021-07-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0111_auto_20210301_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='PlanoIso',
        ),
    ]
