# Generated by Django 3.1.3 on 2021-07-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0112_remove_vivienda_planoiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudgastos',
            name='Soporte',
        ),
        migrations.AddField(
            model_name='solicitudgastos',
            name='NumeroFactura',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
