# Generated by Django 3.1.3 on 2021-09-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0113_auto_20210711_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.CharField(blank=True, choices=[('Presidente', 'Presidente (Pdte)'), ('Cartera', 'Cartera (Ct)'), ('Operario', 'Operario (Ope)'), ('Auxiliar', 'Auxiliar (Aux)'), ('Administrador de sistemas', 'Administrador de sistemas(Dir)')], default='Auxiliar', max_length=100, null=True),
        ),
    ]
