# Generated by Django 3.1.3 on 2021-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0114_auto_20210912_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso - (AC)'), ('NOACCE', 'No acceso - CAMBIO ESTADO - (NOACCE)'), ('NOAC', 'No acceso - CONTROL PRESUPUESTAL - (NOAC)'), ('NOACFA', 'No acceso - FACTURACION - (NOACFA)'), ('NOACRE', 'No acceso - REPORTES - (NOACRE)'), ('NOACP', 'No acceso - PQRS - (NOACP)'), ('NOACSR', 'No acceso - SUSPENCIONES/RECONEXIONES - (NOACSR)'), ('NOACLT', 'No acceso - LISTA TITULARES - (NOACLT)'), ('NOACLP', 'No acceso - LISTA PREDIOS - (NOACLP)'), ('NOACBU', 'No acceso - BUSQUEDAS - (NOACBU)'), ('NOACRT', 'No acceso - REGISTRO TITULAR - (NOACRT)'), ('NOACRP', 'No acceso - REGISTRO PREDIO - (NOACRP)'), ('NOACRPQ', 'No acceso - REGISTRO PQRS - (NOACRPQ)'), ('NOACRPG', 'No acceso - REGISTRO PAGO - (NOACRPG)'), ('NOACMT', 'No acceso - MODIFICAR TITULAR - (NOACMT)'), ('NOACMP', 'No acceso - MODIFICAR PREDIO - (NOACMP)'), ('NOACCT', 'No acceso - CAMBIAR TITULAR - (NOACCT)'), ('NOACMAPA', 'No acceso - CAMBIAR TITULAR - (NOACMAPA)'), ('SUPERADMIN', 'No acceso - ADMINISTRADOR - (SUPERADMIN)'), ('AccessPanel', 'Acceso - Panel de administracion')], max_length=50),
        ),
    ]
