# Generated by Django 3.1.3 on 2021-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0115_auto_20210914_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Departamento',
            field=models.CharField(default='Departamento de sistemas', max_length=50),
            preserve_default=False,
        ),
    ]
