# Generated by Django 3.1.3 on 2021-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0116_usuario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acueducto',
            name='logo',
            field=models.ImageField(default='usuarios/usuario.png', upload_to='usuarios'),
        ),
    ]
