# Generated by Django 3.1.3 on 2021-10-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0117_acueducto_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso - (AC)'), ('AccessVFac', 'Acceso - Modulo ver factura - (NOACCE)'), ('AccessPanel', 'Acceso - Panel de administracion')], max_length=50),
        ),
    ]
