# Generated by Django 3.1.3 on 2021-10-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0118_auto_20211002_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='FechaPago',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='TipoPermiso',
            field=models.CharField(choices=[('AC', 'Acceso - (AC)'), ('AccessVFac', 'Acceso - Modulo ver factura (AccessVFac)'), ('AccessPanel', 'Acceso - Panel de administracion (AccessPanel)')], max_length=50),
        ),
    ]
