# Generated by Django 3.1.3 on 2022-02-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0119_auto_20211025_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='consumomin',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='consumotipo1',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='consumotipo2',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='consumotipo3',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
