# Generated by Django 3.1.3 on 2022-02-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0120_auto_20220216_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='consumotipo1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='consumotipo2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='consumotipo3',
            field=models.IntegerField(null=True),
        ),
    ]
