# Generated by Django 3.1.3 on 2022-02-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0121_auto_20220216_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='Potipo1',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='Potipo2',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='Potipo3',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='consumomin',
            field=models.IntegerField(null=True),
        ),
    ]
