# Generated by Django 3.1.3 on 2022-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0122_auto_20220216_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='FichaCastral',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
