# Generated by Django 3.1.3 on 2022-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0123_vivienda_fichacastral'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='Descripcion',
            field=models.CharField(default='Consumo', max_length=20),
            preserve_default=False,
        ),
    ]
