# Generated by Django 3.1.3 on 2022-02-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0124_pagos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroOrdenes',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Estado', models.CharField(max_length=30)),
                ('Valor', models.CharField(max_length=30)),
                ('IdOrdenT', models.CharField(max_length=30)),
                ('TipoOrden', models.CharField(max_length=30)),
                ('IdEstadoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.estadocuenta')),
            ],
            options={
                'verbose_name': 'Novedad general',
                'verbose_name_plural': 'Novedades generales',
            },
        ),
    ]
