# Generated by Django 3.1.3 on 2022-02-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0125_cobroordenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobroordenes',
            options={'verbose_name': 'Cobro orden', 'verbose_name_plural': 'Cobro ordenes SR'},
        ),
    ]
