# Generated by Django 3.1.3 on 2022-02-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0126_auto_20220224_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOrdenes',
            fields=[
                ('IdPagoSR', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPago', models.DateTimeField(auto_now=True)),
                ('Valor', models.CharField(max_length=30)),
                ('IdOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.cobroordenes')),
                ('IdVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.vivienda')),
            ],
            options={
                'verbose_name': 'Pago orden',
                'verbose_name_plural': 'PagoOrdenes',
            },
        ),
    ]
