# Generated by Django 3.1.3 on 2022-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0127_pagoordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='TarifaReconexion',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='TarifaSuspencion',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
