# Generated by Django 3.1.3 on 2022-02-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0128_auto_20220224_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='consumotipo3',
        ),
    ]
