# Generated by Django 3.1.3 on 2022-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0129_remove_tarifa_consumotipo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='Mantenimiento',
            field=models.CharField(default=3000, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Ciclo',
            field=models.CharField(choices=[('2', 'Ciclo pasonivel viejo'), ('3', 'Ciclo Barrio nuevo'), ('4', 'Ciclo caimalito via principal'), ('5', 'Ciclo 20 julio'), ('6', 'Ciclo la loma'), ('7', 'Ciclo caimalito 2 via principal'), ('8', 'Ciclo via nacional'), ('9', 'Conexion planta de tratamiento')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='Direccion',
            field=models.CharField(choices=[('Pasonivel Viejo', 'Sector pasonivel viejo'), ('Pasonivel Destapada', 'Sector pasonivel destapada'), ('Caimalito Centro', 'Sector caimalito centro'), ('Barrio Nuevo', 'Sector barrio nuevo'), ('20 de julio', 'Sector 20 de julio'), ('Pasonivel la loma', 'Sector pasonivel la loma'), ('Hacienda', 'Hacienda'), ('Via nacional', 'Sector Via nacional'), ('Caimalito centro dos', 'Sector caimalito centro dos'), ('Destapada', 'Sector destapada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='EstadoServicio',
            field=models.CharField(choices=[('Operativo', 'Operativo (OP)'), ('Suspendido', 'Suspendido (SP)'), ('Mantenimiento', 'Mantenimiento (MT)'), ('Retirado', 'Retirado  (RD)'), ('Conexion nueva', 'Conexion nueva (CN)')], default='EC', max_length=60),
        ),
    ]
