# Generated by Django 3.1.3 on 2022-05-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0130_auto_20220528_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='Recargo',
            field=models.CharField(default=500, max_length=15),
            preserve_default=False,
        ),
    ]
