# Generated by Django 3.1.3 on 2022-05-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0131_tarifa_recargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='Potipo3',
        ),
    ]
