# Generated by Django 3.1.3 on 2022-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0132_remove_tarifa_potipo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='Potipo1',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='Potipo2',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
