# Generated by Django 3.1.3 on 2022-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0133_auto_20220528_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Estrato',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='Matricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='casa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='ciclo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccionentrega',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='estadoservicio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombretitular',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodofacturado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='piso',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tiposerivio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
