# Generated by Django 3.1.3 on 2022-05-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0134_auto_20220529_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='aporteporconsumo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='conceptomatricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cuotasmatricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='reconexion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='suspencion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
