# Generated by Django 3.1.3 on 2022-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0135_auto_20220529_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Fechasuspencion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='facturasvencidas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='FechaExpe',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='FechaLimite',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='TotalConsumo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
