# Generated by Django 3.1.3 on 2022-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0136_auto_20220529_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Fechasuspencion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
