# Generated by Django 3.1.3 on 2022-05-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0137_auto_20220529_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Fechasuspencion',
        ),
    ]
