# Generated by Django 3.1.3 on 2022-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0138_remove_factura_fechasuspencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Fechasuspencion',
            field=models.DateTimeField(null=True),
        ),
    ]
