# Generated by Django 3.1.3 on 2022-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0139_factura_fechasuspencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nit', models.CharField(max_length=30)),
                ('Razonsocial', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Telefono', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Tipoproveedor', models.CharField(max_length=100)),
            ],
        ),
    ]
