# Generated by Django 3.1.3 on 2022-10-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAL', '0140_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadesSistema',
            fields=[
                ('IdNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAAL.usuario')),
            ],
        ),
    ]
